#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const rootDir = path.resolve(dir, "../..")

process.chdir(dir)

import pkg from "../package.json"

const version = process.env.OPENCODE_COLLAB_VERSION ?? pkg.version
const shouldPublish = process.argv.includes("--publish")
const skipWebUI = process.argv.includes("--skip-embed-web-ui")
const platformArg = process.argv.find((a) => a.startsWith("--platform="))?.split("=")[1]

const ALL_TARGETS = [
  { os: "darwin", cpu: "arm64", target: "bun-darwin-arm64" },
  { os: "darwin", cpu: "x64", target: "bun-darwin-x64" },
  { os: "linux", cpu: "arm64", target: "bun-linux-arm64" },
  { os: "linux", cpu: "x64", target: "bun-linux-x64" },
  { os: "win32", cpu: "x64", target: "bun-windows-x64" },
]

const targets = platformArg
  ? ALL_TARGETS.filter((t) => t.os === platformArg || t.target === platformArg)
  : ALL_TARGETS

if (targets.length === 0) {
  console.error("No matching targets found for:", platformArg)
  console.error("Available: darwin, linux, win32")
  process.exit(1)
}

console.log(`Building opencode-collab v${version}`)
console.log(`Targets: ${targets.map((t) => t.target).join(", ")}`)

// ---------- Step 1: Generate models snapshot ----------
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
console.log("Generated models-snapshot.js")

// ---------- Step 2: Load migrations ----------
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), { withFileTypes: true })
)
  .filter((entry) => entry.isDirectory() && /^\d{14}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// ---------- Step 3: Build embedded web UI ----------
let embeddedFileMap: string | null = null
if (!skipWebUI) {
  console.log("Building Web UI...")
  const appDir = path.join(dir, "../../packages/app")
  const dist = path.join(appDir, "dist")
  await $`bun run --cwd ${appDir} build`
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dist })))
    .map((file) => file.replaceAll("\\", "/"))
    .sort()
  const imports = files.map((file, i) => {
    const spec = path.relative(dir, path.join(dist, file)).replaceAll("\\", "/")
    return `import file_${i} from ${JSON.stringify(spec.startsWith(".") ? spec : `./${spec}`)} with { type: "file" };`
  })
  const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)
  embeddedFileMap = [
    `// Import all files as file_$i with type: "file"`,
    ...imports,
    `// Export with original mappings`,
    `export default {`,
    ...entries,
    `}`,
  ].join("\n")
  console.log(`Embedded ${files.length} web UI files`)
}

// ---------- Step 4: Build binaries for all platforms ----------
console.log("Building native binaries...")
await $`rm -rf dist/collab`

await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`

const plugin = createSolidTransformPlugin()

const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
const workerPath = "./src/cli/cmd/tui/worker.ts"

const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

const platformPackages: { name: string; version: string }[] = []

for (const { os, cpu, target } of targets) {
  const pkgName = `opencode-collab-${os === "win32" ? "windows" : os}-${cpu}`
  const binName = os === "win32" ? "opencode.exe" : "opencode"
  console.log(`  Building ${target} -> ${pkgName}`)

  await $`mkdir -p dist/collab/${pkgName}/bin`

  const buildResult = await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [plugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: target as any,
      outfile: `dist/collab/${pkgName}/bin/${binName}`,
      execArgv: [`--user-agent=opencode-collab/${version}`, "--use-system-ca", "--"],
      windows: {},
    },
    files: {
      ...(embeddedFileMap ? { "opencode-web-ui.gen.ts": embeddedFileMap } : {}),
    },
    entrypoints: [
      "./src/index.ts",
      parserWorker,
      workerPath,
      ...(embeddedFileMap ? ["opencode-web-ui.gen.ts"] : []),
    ],
    define: {
      OPENCODE_VERSION: `'${version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OPENCODE_CHANNEL: `'latest'`,
      OPENCODE_LIBC: `''`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
    },
  })

  if (!buildResult.success) {
    console.error(`Build failed for ${target}:`, buildResult.logs)
    process.exit(1)
  }

  const platformPkg = {
    name: pkgName,
    version,
    description: `opencode-collab binary for ${os} ${cpu}`,
    license: "MIT",
    os: [os],
    cpu: [cpu],
    repository: {
      type: "git",
      url: "https://github.com/anomalyco/opencode",
    },
  }
  await Bun.write(`dist/collab/${pkgName}/package.json`, JSON.stringify(platformPkg, null, 2))
  platformPackages.push({ name: pkgName, version })
}

console.log("All builds complete")

// ---------- Step 5: Create main wrapper package ----------
const mainPkg = {
  name: "opencode-collab",
  version,
  description: "opencode with real-time collaboration — zero-config network access",
  license: "MIT",
  bin: {
    "opencode-collab": "./bin/opencode-collab.js",
  },
  scripts: {
    postinstall: "node install.js",
  },
  optionalDependencies: Object.fromEntries(platformPackages.map((p) => [p.name, p.version])),
  repository: {
    type: "git",
    url: "https://github.com/anomalyco/opencode",
  },
  keywords: ["opencode", "ai", "collaboration", "web", "cli"],
}
await $`mkdir -p dist/collab/opencode-collab/bin`
await Bun.write("dist/collab/opencode-collab/package.json", JSON.stringify(mainPkg, null, 2))

const wrapperJs = `#!/usr/bin/env node
const { execFileSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const platform = process.platform;
const arch = process.arch;

let binName;
if (platform === 'darwin') {
  binName = arch === 'arm64' ? 'opencode-collab-darwin-arm64' : 'opencode-collab-darwin-x64';
} else if (platform === 'linux') {
  binName = arch === 'arm64' ? 'opencode-collab-linux-arm64' : 'opencode-collab-linux-x64';
} else if (platform === 'win32') {
  binName = 'opencode-collab-windows-x64';
} else {
  console.error('Unsupported platform:', platform, arch);
  process.exit(1);
}

const binPath = path.join(
  __dirname,
  '..',
  '..',
  binName,
  'bin',
  platform === 'win32' ? 'opencode.exe' : 'opencode'
);

if (!fs.existsSync(binPath)) {
  console.error('Binary not found:', binPath);
  console.error('Please ensure the package was installed correctly.');
  process.exit(1);
}

execFileSync(binPath, process.argv.slice(2), { stdio: 'inherit' });
`

await Bun.write("dist/collab/opencode-collab/bin/opencode-collab.js", wrapperJs)

const installJs = `#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const platform = process.platform;
const arch = process.arch;

const platformMap = {
  'darwin-arm64': 'opencode-collab-darwin-arm64',
  'darwin-x64': 'opencode-collab-darwin-x64',
  'linux-arm64': 'opencode-collab-linux-arm64',
  'linux-x64': 'opencode-collab-linux-x64',
  'win32-x64': 'opencode-collab-windows-x64',
};

const key = platform + '-' + arch;
const needed = platformMap[key];

if (!needed) {
  console.log('No binary available for platform:', key);
  process.exit(0);
}

for (const [pkg, neededPkg] of Object.entries(platformMap)) {
  if (pkg !== key) {
    const pkgPath = path.join(__dirname, '..', neededPkg);
    if (fs.existsSync(pkgPath)) {
      try {
        fs.rmSync(pkgPath, { recursive: true });
        console.log('Removed unnecessary package:', neededPkg);
      } catch (e) {
        // ignore
      }
    }
  }
}
`

await Bun.write("dist/collab/opencode-collab/install.js", installJs)

console.log("Created wrapper package")

// ---------- Step 6: Publish ----------
if (shouldPublish) {
  console.log(`\nPublishing packages...`)

  for (const { name } of platformPackages) {
    console.log(`  Publishing ${name}...`)
    await $`npm publish --access public`.cwd(`dist/collab/${name}`)
  }

  console.log(`  Publishing opencode-collab (main package)...`)
  await $`npm publish --access public`.cwd("dist/collab/opencode-collab")

  console.log("\nAll packages published!")
} else {
  console.log("\nDry run complete. Packages ready at dist/collab/")
  console.log("To publish: bun run script/publish-collab.ts --publish")
  console.log(`\nPackages to be published:`)
  for (const { name } of platformPackages) {
    console.log(`  - ${name}`)
  }
  console.log(`  - opencode-collab (main wrapper)`)
}
